### PR TITLE
fix play seq parsing

### PR DESCRIPTION
**Pull request by ccbrown**
PlaySeq is sometimes a float.

### CODE REVIEW

**Review by crhanlon — APPROVED** [review]

**Comment by crhanlon** [comment]
@ccbrown the test file you showed could cause issues with the cumulative points/stats.  This is a case where the play IDs do not strictly increase.  See here https://github.com/sportsball-ai/fusion-feed/pull/67

**Comment by ccbrown** [comment]
> @ccbrown the test file you showed could cause issues with the cumulative points/stats. This is a case where the play IDs do not strictly increase. See here [sportsball-ai/fusion-feed#67](https://github.com/sportsball-ai/fusion-feed/pull/67)

Yeah, I see. Can you either go ahead and fix it or make an issue to fix it next sprint?

**Comment by crhanlon** [comment]
Probably don't want to fix it before the game tonight (unless we're getting the wrong data, then I can try), but I should be able to fix it this sprint

**Comment by ccbrown** [comment]
Yeah don't worry about it for tonight.

**Pull request merged**
