### PR TITLE
Xml performance

### PR DESCRIPTION
**Pull request by ccbrown**
Through the magic of code generation, here's a 30% speedup in XML decode times. The code generation is done in https://github.com/sportsball-ai/go-xml-gen.

Screen Shot 2021-07-26 at 10 12 05 PM

### CODE REVIEW

**Comment by crhanlon** [comment]
@ccbrown how robust is this?  Have you tested it against the stat files we have cached?

**Comment by ccbrown** [comment]
Well, CI tests it against the over 500 files in this repo and none of them fail to decode.

The generated code isn't too hard to review manually for correctness. Take a look and let me know if it looks too risky to you.

**Comment by crhanlon** [comment]
It looks good for the most part, it's just ~1000 lines of code decoding a structure and might be easy for me to miss something small.  Could we just have a script to iterate over all of the files we need to decode and ensure it passes against them?

**Comment by ccbrown** [comment]
That's kind of what the test corpus here is meant to be already. What's missing?

**Comment by crhanlon** [comment]
I guess that works, I'm just worried that there are heavy dependencies on this decoding everything correctly, and think it's better to be more cautious for something like this to feel more confident.

**Comment by ccbrown** [comment]
I agree. This terrifies me a little. But I just can't think of any big gaps in the tests here. stat_file_test.go ensures that:

* All cumulative stat files from at least two past seasons decode without error
* All incremental stat files from a game decode without error and reconstruct identically to that game's cumulative stat file
* The cumulative stat file parsed from a game is identical to the parsed JSON stat file for that game

The tests are pretty good, so I'm gonna trust them.

**Comment by crhanlon** [comment]
Okay, can we just be deliberate about having extensive smoke tests when fusion feed upgrades to this version?  Particularly with the cloud sim.

**Comment by ccbrown** [comment]
Yep. @dskart what do you think about this? Is the 30% speedup worth it?

**Review by dskart — APPROVED** [review]
I think the tests are as good as they can be, I am ok with this

**Pull request merged**
